routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::name('website.')->group(function () {
    Route::get('/auth/login', 'WebController@login')->name('login');
    Route::post('/auth/login', 'WebController@loginPost')->name('login');

    Route::get('/auth/activate/{token}', 'WebController@activateAccount')->name('activate-account');

    Route::get('/auth/register', 'WebController@register')->name('register');
    Route::post('/auth/register', 'WebController@registerPost')->name('register');

    Route::get('/auth/logout', 'WebController@logout')->name('logout');

    Route::get('/', 'WebController@home')->name('home');
    Route::post('upload', 'WebController@upload')->name('upload');

    Route::get('/account', 'WebController@account')->name('account');
    Route::get('/account/images', 'WebController@accountImages')->name('account.images');
    Route::get('/account/images/{picture}/destroy', 'WebController@accountImagesDestory')->name('account.images-destroy');
    Route::get('/account/setting', 'WebController@accountSetting')->name('account.setting');
    Route::post('/account/setting', 'WebController@accountSettingPost')->name('account.setting');

    Route::get('/{slug}', 'WebController@view')->name('view');
    Route::post('/{slug}', 'WebController@viewPost')->name('view');

    Route::get('/page/{slug}', 'WebController@page')->name('page');
});

Route::name('dashboard.')->namespace("Dashboard")->prefix('d')->group(function () {
    Route::get('overview', 'OverviewController@index')->name('overview');

    Route::resource('users', 'UserController')->names([
        'index' => 'users'
    ]);
    Route::resource('images', 'ImageController')->names([
        'index' => 'images'
    ]);
    Route::resource('pages', 'PageController')->names([
        'index' => 'pages'
    ]);
    Route::resource('settings', 'SettingController')->names([
        'index' => 'settings'
    ]);
});

resources/views/frontend/pages/account/_menu.blade.php
<div class="custom-list-group">
    <a href="{{route('website.account.images')}}" class="list-group-item list-group-item-action @if(Request::is('account/images*')) active @endif">My Uploads</a>
    <a href="{{route('website.account.setting')}}" class="list-group-item list-group-item-action @if(Request::is('account/setting*')) active @endif">Setting</a>
</div>

resources/views/frontend/pages/account/image.blade.php
@extends('frontend.layout.layout')
@section('content')
    <div class="mt-5 row">
        <div class="col-md-4 col-lg-3 col-xl-3">
            @include('frontend.pages.account._menu')
        </div>
        <div class="col-md-8 col-lg-9">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif
            <div class="card-columns">
                @foreach($pictures as $photo)
                    <div class="card">
                        <img src="{{asset('storage/'.$photo->thumbnail_path_url)}}" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title h6">{{$photo->name}}</h5>
                            <a href="{{route('website.view', ['slug'=>$photo->uuid])}}" class="btn btn-primary">View /
                                Edit</a>
                            <a href="{{route('website.account.images-destroy', ['picture'=>$photo->uuid])}}" class="btn btn-outline-danger">Delete</a>
                        </div>
                    </div>
                @endforeach
            </div>
            <div class="mt-3">{{$pictures->links()}}</div>
        </div>
    </div>
@endsection

resources/views/frontend/pages/account/setting.blade.php
@extends('frontend.layout.layout')
@section('content')
    <div class="mt-5 row">
        <div class="col-md-4 col-lg-3 col-xl-3">
            @include('frontend.pages.account._menu')
        </div>
        <div class="col-md-8 col-lg-9">
            @if (session('success'))
                <div class="alert alert-success">
                    {{ session('success') }}
                </div>
            @endif

            <form method="post" action="">
                @csrf
                <div class="form-group">
                    <label>Full Name</label>
                    <input class="form-control @error('fullname') is-invalid @enderror" name="fullname" value="{{old('fullname', $user->name)}}">
                    @error("fullname")
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label>Email</label>
                    <div class="form-control">{{$user->email}}</div>
                </div>

                <div class="form-group">
                    <label>New Password</label>
                    <input class="form-control @error('password') is-invalid @enderror" name="password" value="">
                    @error("password")
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>

                <div class="form-group">
                    <label>New Password Confirm</label>
                    <input class="form-control" name="password_confirmation" value="">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary float-right">Save Account</button>
                </div>
            </form>
        </div>
    </div>
@endsection