routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::name('website.')->group(function () {
    Route::get('/auth/login', 'WebController@login')->name('login');
    Route::post('/auth/login', 'WebController@loginPost')->name('login');

    Route::get('/auth/activate/{token}', 'WebController@activateAccount')->name('activate-account');

    Route::get('/auth/register', 'WebController@register')->name('register');
    Route::post('/auth/register', 'WebController@registerPost')->name('register');

    Route::get('/auth/logout', 'WebController@logout')->name('logout');

    Route::get('/', 'WebController@home')->name('home');
    Route::post('upload', 'WebController@upload')->name('upload');

    Route::get('/account', 'WebController@account')->name('account');
    Route::get('/account/images', 'WebController@accountImages')->name('account.images');
    Route::get('/account/images/{picture}/destroy', 'WebController@accountImagesDestory')->name('account.images-destroy');
    Route::get('/account/setting', 'WebController@accountSetting')->name('account.setting');
    Route::post('/account/setting', 'WebController@accountSettingPost')->name('account.setting');

    Route::get('/{slug}', 'WebController@view')->name('view');
    Route::post('/{slug}', 'WebController@viewPost')->name('view');

    Route::get('/page/{slug}', 'WebController@page')->name('page');
});

Route::name('dashboard.')->namespace("Dashboard")->prefix('d')->group(function () {
    Route::get('overview', 'OverviewController@index')->name('overview');

    Route::resource('users', 'UserController')->names([
        'index' => 'users'
    ]);
    Route::resource('images', 'ImageController')->names([
        'index' => 'images'
    ]);
    Route::resource('pages', 'PageController')->names([
        'index' => 'pages'
    ]);
    Route::resource('settings', 'SettingController')->names([
        'index' => 'settings'
    ]);
});

resources/views/backend/pages/pages/create.blade.php
@extends('backend.layout.layout')
@section('content')
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <form method="post" action="{{route('dashboard.pages.store')}}">
        @csrf
        @method('POST')

        <h1 class="text-white h3 mb-5">Add New Page</h1>

        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <label for="">Title</label>
                    <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{old('title')}}">
                    @error("title")
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <textarea name="article" cols="30" rows="10" class="summernote">{{old('article')}}</textarea>
                @error("article")
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
                <div class="mt-4">
                    <button type="submit" class="btn btn-primary float-right">Save</button>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/backend/pages/pages/edit.blade.php
@extends('backend.layout.layout')
@section('content')
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <h1 class="text-white h3 mb-5">Edit Page</h1>

    <form method="post" action="{{route('dashboard.pages.update',['page'=>$page->id])}}">
        @csrf
        @method('PATCH')
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <label for="">Title</label>
                    <input type="text" name="title" class="form-control @error('title') is-invalid @enderror" value="{{old('title', $page->title)}}">
                    @error("title")
                    <div class="invalid-feedback">
                        {{ $message }}
                    </div>
                    @enderror
                </div>
                <textarea name="article" cols="30" rows="10" class="summernote">{{old('article', $page->article)}}</textarea>
                @error("article")
                <div class="invalid-feedback">
                    {{ $message }}
                </div>
                @enderror
                <div class="mt-4">
                    <button type="submit" class="btn btn-primary float-right">Save</button>
                </div>
            </div>
        </div>
    </form>
@endsection

resources/views/backend/pages/pages/index.blade.php
@extends('backend.layout.layout')
@section('content')
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            <a href="{{route('dashboard.pages.create')}}" class="btn btn-primary">Add New Page</a>
        </div>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($pages as $page)
                <tr>
                    <th width="50" scope="row">{{$page->id}}</th>
                    <td>{{$page->title}}</td>
                    <td width="200" class="text-right">
                        <form method="post" action="{{route('dashboard.pages.destroy', ['page'=>$page->id])}}">
                            @csrf
                            @method('DELETE')
                            <a href="{{route('dashboard.pages.edit', ['page'=>$page->id])}}"
                               class="btn btn-outline-primary btn-sm">Edit </a>
                            <button class="btn btn-outline-danger btn-sm" type="submit">Delete</button>

                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>

    <div class="mt-4">
        {{--        {{$users->links()}}--}}
    </div>
@endsection