routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::name('website.')->group(function () {
    Route::get('/auth/login', 'WebController@login')->name('login');
    Route::post('/auth/login', 'WebController@loginPost')->name('login');

    Route::get('/auth/activate/{token}', 'WebController@activateAccount')->name('activate-account');

    Route::get('/auth/register', 'WebController@register')->name('register');
    Route::post('/auth/register', 'WebController@registerPost')->name('register');

    Route::get('/auth/logout', 'WebController@logout')->name('logout');

    Route::get('/', 'WebController@home')->name('home');
    Route::post('upload', 'WebController@upload')->name('upload');

    Route::get('/account', 'WebController@account')->name('account');
    Route::get('/account/images', 'WebController@accountImages')->name('account.images');
    Route::get('/account/images/{picture}/destroy', 'WebController@accountImagesDestory')->name('account.images-destroy');
    Route::get('/account/setting', 'WebController@accountSetting')->name('account.setting');
    Route::post('/account/setting', 'WebController@accountSettingPost')->name('account.setting');

    Route::get('/{slug}', 'WebController@view')->name('view');
    Route::post('/{slug}', 'WebController@viewPost')->name('view');

    Route::get('/page/{slug}', 'WebController@page')->name('page');
});

Route::name('dashboard.')->namespace("Dashboard")->prefix('d')->group(function () {
    Route::get('overview', 'OverviewController@index')->name('overview');

    Route::resource('users', 'UserController')->names([
        'index' => 'users'
    ]);
    Route::resource('images', 'ImageController')->names([
        'index' => 'images'
    ]);
    Route::resource('pages', 'PageController')->names([
        'index' => 'pages'
    ]);
    Route::resource('settings', 'SettingController')->names([
        'index' => 'settings'
    ]);
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    const ROLE_ADMINISTRATOR = 1;
    const ROLE_USER = 2;

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function images(){
        return $this->hasMany(Image::class);
    }
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Auth;
use App;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::paginate();
        return view('backend.pages.users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);

        return view('backend.pages.users.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'fullname' => "required",
            "email" => "required|unique:users,email,$id"
        ]);


        $user = User::findOrFail($id);
        $user->name = $request->fullname;
        $user->email = $request->email;
        $user->save();

        return redirect()->route('dashboard.users')->with('success', 'User Account Updated.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!App::environment('demo')) {
            $user = User::findOrFail($id);
            if ($user->id != Auth::user()->id) {
                $user->delete();
                return redirect()->back()->with('success', 'User Deleted');
            } else {
                return redirect()->back()->with('success', 'Its Your Account, you cannot delete your account.');
            }
        } else {
            return redirect()->back()->with('success', 'cannot delete on demo account.');
        }
    }
}

resources/views/backend/pages/users/edit.blade.php
@extends('backend.layout.layout')
@section('content')
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <div class="row">
        <div class="col-md-6">
            <form action="{{route('dashboard.users.update',["user"=>$user->id])}}" method="post">
                @csrf
                @method('PATCH')
                <div class="card bg-darker text-light">
                    <div class="card-body">
                        <h3 class="mb-4">Edit User</h3>
                        <div class="form-group ">
                            <label for="">Full Name</label>
                            <input type="text" class="form-control @error('fullname') is-invalid @enderror"
                                   name="fullname"
                                   value="{{old('fullname', $user->name)}}">
                            @error("fullname")
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group ">
                            <label for="">Email</label>
                            <input type="email" class="form-control @error('email') is-invalid @enderror" name="email"
                                   value="{{old('email', $user->email)}}">
                            @error("email")
                            <div class="invalid-feedback">
                                {{ $message }}
                            </div>
                            @enderror
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary float-right">Update User</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/backend/pages/users/index.blade.php
@extends('backend.layout.layout')
@section('content')
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif

    <div class="card-columns">
        @foreach($users as $user)
            <div class="card bg-darker">
                <div class="card-body text-muted">
                    <h3 class="h5 text-white">{{$user->name}}</h3>
                    <p>{{$user->email}}</p>
                    <form class="" method="post" action="{{route('dashboard.users.destroy', ['user'=>$user->id])}}">
                        @csrf
                        @method('DELETE')
                        <div class="">
                            <a href="{{route('dashboard.users.edit', ['user'=>$user->id])}}">
                                <button type="button" class="btn btn-primary">Edit</button>
                            </a>

                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
        @endforeach
    </div>

    <div class="mt-4">
        {{$users->links()}}
    </div>
@endsection