routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::name('website.')->group(function () {
    Route::get('/auth/login', 'WebController@login')->name('login');
    Route::post('/auth/login', 'WebController@loginPost')->name('login');

    Route::get('/auth/activate/{token}', 'WebController@activateAccount')->name('activate-account');

    Route::get('/auth/register', 'WebController@register')->name('register');
    Route::post('/auth/register', 'WebController@registerPost')->name('register');

    Route::get('/auth/logout', 'WebController@logout')->name('logout');

    Route::get('/', 'WebController@home')->name('home');
    Route::post('upload', 'WebController@upload')->name('upload');

    Route::get('/account', 'WebController@account')->name('account');
    Route::get('/account/images', 'WebController@accountImages')->name('account.images');
    Route::get('/account/images/{picture}/destroy', 'WebController@accountImagesDestory')->name('account.images-destroy');
    Route::get('/account/setting', 'WebController@accountSetting')->name('account.setting');
    Route::post('/account/setting', 'WebController@accountSettingPost')->name('account.setting');

    Route::get('/{slug}', 'WebController@view')->name('view');
    Route::post('/{slug}', 'WebController@viewPost')->name('view');

    Route::get('/page/{slug}', 'WebController@page')->name('page');
});

Route::name('dashboard.')->namespace("Dashboard")->prefix('d')->group(function () {
    Route::get('overview', 'OverviewController@index')->name('overview');

    Route::resource('users', 'UserController')->names([
        'index' => 'users'
    ]);
    Route::resource('images', 'ImageController')->names([
        'index' => 'images'
    ]);
    Route::resource('pages', 'PageController')->names([
        'index' => 'pages'
    ]);
    Route::resource('settings', 'SettingController')->names([
        'index' => 'settings'
    ]);
});

resources/views/frontend/layout/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{asset('css/app.css')}}" crossorigin="anonymous">

    <title>{{config('app.name')}} - {{setting('website.tagline')}}</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
<body class="{{$routeName ?? ""}}">
<div class="home-cover">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{route('website.home')}}">{{config('app.name')}}</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            About
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @foreach($navPages as $page)
                                <a class="dropdown-item" href="{{route('website.page', ['slug'=> $page->slug])}}">{{$page->title}}</a>
                            @endforeach
                        </div>
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto">
                    <li class="nav-item @if(Request::is('/')) active @endif">
                        <a class="nav-link" href="{{route('website.home')}}">Upload <span
                                    class="sr-only">(current)</span></a>
                    </li>

                    @if(Auth::check())
                        <li class="nav-item dropdown @if(Request::is('account*')) active @endif">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Account
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                @if(Auth::user()->role==\App\User::ROLE_ADMINISTRATOR)
                                    <a class="dropdown-item" href="{{route('dashboard.overview')}}">Admin Dashboard</a>
                                @endif
                                <a class="dropdown-item" href="{{route('website.account.images')}}">My Account</a>
                                <a class="dropdown-item" href="{{route('website.account.setting')}}">Setting</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{route('website.logout')}}">Logout</a>
                            </div>
                        </li>
                    @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{route('website.login')}}">Sign In</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link pt-0 pb-0" href="{{route('website.register')}}">
                                <button class="btn btn-primary">Create Account</button>
                            </a>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @yield('content')
    </div>
</div>

<script src="{{asset('js/app.js')}}" crossorigin="anonymous"></script>
{!! setting('website.analytics') !!}
</body>
</html>